services:
  - type: web
    name: final-approver-interface-backend
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
